runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: ssl
  version: latest
  
#https://github.com/shazow/urllib3/issues/618#issuecomment-101795512
env_variables:
  GAE_USE_SOCKETS_HTTPLIB : 'anyvalue'  

# [START handlers]
handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.app
# [END handlers]
